version: '3'

services:
  client: 
    image: node:16.15.0
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /client
    working_dir: /client
    command: bash -c "npm install && npm run dev"

  api:
    image: node:16.15.0
    ports:
      - 3000:3000
    environment:
      - MONGODB_USER=futureproof
      - MONGODB_HOST=db
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=usershabits
      - COHORT=shaw
      - MONGODB_PORT=5432
    volumes:
      - type: bind
        source: ./backend
        target: /server
    working_dir: /server
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - "mongodb-data:/data/db"
      # - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - MONGODB=usershabits
      - MONGODB_USER=futureproof
      - MONGODB_PASSWORD=password

volumes:
  mongodb-data:
